[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vdsc-url-generator"
version = "1.0.0"
description = "Gerador de Url pré-assinada para upload e downloads de vídeos."
authors = [
    { name="Tito Parizotto", email="titoparizotto@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "boto3",
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "moto"
]

[project.urls]
"Homepage" = "https://github.com/11soat-hackton-videoslice/ms-video-url-generator"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
markers = [
    "unit: marca testes unitários"
]
